# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movieCatalog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movieCatalog
  pod "TinyConstraints"
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Alamofire', '~> 4.4'
  pod 'Cache'
  pod 'Imaginary'
  pod 'youtube-ios-player-helper'
  
end
